services:
  nhyira-web:
    build:
      context: ./
    ports:
      - "80:80"  # Expõe a porta 80 do contêiner
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped  
