version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"   # Porta para HTTP
      - "443:443" # Porta para HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs # Certificados SSL
      - ./html:/usr/share/nginx/html # Código da aplicação
    networks:
      - webnet
networks:
  webnet:
