services:
  nhyira-web:
    build:
      context: ./ 
    ports:
      - "80:80"  
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
