services:
  nhyira-web:
    build:
      context: ./
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
