  nhyira-web:
    image: willdantas/nhyira-web:00.00
    ports:
      - "80:80"  # Expor a porta 80 para HTTP
      - "443:443"  # Expor a porta 443 para HTTPS
    volumes:
      - ./frontend:/home/ubuntu/frontend  # Montar a pasta frontend
    environment:
      - NODE_ENV=production  # Definir variáveis de ambiente, se necessário
    restart: unless-stopped  # Garantir que o serviço reinicie em caso de falha
