services:
  nhyira-web:
    build:
      context: ./
    ports:
      - "443:443"  # Expondo apenas a porta HTTPS
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
