services:
  nhyira-web:
    build:
      context: ./frontend  # Diretório onde está o Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
