name: CI/CD Front End - Nhyira

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build e Push da Imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nhyira-web:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nhyira-web:latest

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./infraNhyira

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infraNhyira

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infraNhyira

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infraNhyira



    
    